export const gbpLocation = {
  storeName: "Pleasant Cannabis",
  domain: "www.pleasantcannabis.ca",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "758 Mt Pleasant Rd, Toronto, ON M4S 2N6",
  streetAddress: "758 Mt Pleasant Rd",
  postalCode: "M4S 2N6",
  phone: "(437) 427-0758",
  phoneIntl: "+14374270758",
  neighborhood: "Mount Pleasant / Midtown Toronto",
  nearbyAreas: ["Mount Pleasant", "Midtown Toronto", "Davisville", "Yonge and Eglinton", "Leaside", "Moore Park", "Rosedale", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.7045",
  longitude: "-79.3915",
  hours: ["Open 24 Hours"],
  seoTitle: "Pleasant Cannabis | Weed Dispensary in Toronto",
  metaDescription: "Pleasant Cannabis is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Mount Pleasant", "Midtown Toronto", "Davisville"],
  introVariant: "Pleasant Cannabis is a neighborhood weed dispensary in Toronto at 758 Mt Pleasant Rd near Midtown Toronto. Adults 19+ can browse menu categories including flower, pre-rolls, edibles, THC vapes, concentrates, and smoking accessories before visiting.",
  neighborhoodDescription: "Located in the vibrant Mount Pleasant / Midtown Toronto district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking is available along Mount Pleasant Road",
  transitNote: "Served by local TTC bus routes along Mount Pleasant Road and Eglinton Avenue.",
  sectionTitle: "Serving Customers Near Mount Pleasant and Midtown Toronto"
};
